import test from 'node:test';
import assert from 'node:assert/strict';
import { isKnownTeamName, russianTeamName } from '../src/v23.2/team-registry.mjs';

const CURRENT_FEED_RAW_NAMES = Object.freeze([
  'AEK Larnaca',
  'AF Elbasani',
  'AGF',
  'Apollon Limassol',
  'Astana',
  'Atert Bissen',
  'Atlètic Club Escaldes',
  'BATE Borisov',
  'Başakşehir FK',
  'Beitar Jerusalem',
  'Bohemian FC',
  'Brighton & Hove Albion',
  'CFR 1907 Cluj',
  'CSKA Sofia',
  'Caernarfon Town',
  'Coleraine FC',
  "Connah's Quay Nomads",
  'Crystal Palace',
  'DAC 1904',
  'Debreceni VSC',
  'Derry City',
  'Differdange FC 03',
  'Dinamo City',
  'Dinamo Minsk',
  'Dinamo Tbilisi',
  'Dukagjini',
  'ETO FC Győr',
  'Europa FC',
  'FC Alashkert',
  'FC CSKA 1948 Sofia',
  'FC Dila Gori',
  'FC Drita',
  'FC Hegelmann',
  'FC Hradec Králové',
  'FC Iberia 1999',
  'FC Koper',
  'FC Lugano',
  'FC Malisheva',
  'FC Milsami Orhei',
  'FC Noah',
  'FC Nordsjælland',
  'FC Petrocub Hîncesti',
  'FC Santa Coloma',
  'FC Sion',
  'FC Spartak Trnava',
  'FC St. Gallen 1879',
  'FC Thun',
  'FC Tobyl',
  'FC Torpedo Kutaisi',
  'FC Twente',
  'FC Universitatea Cluj',
  'FC Vaduz',
  'FC Viktoria Plzeň',
  'FC Zimbru Chişinău',
  'FCI Levadia Tallinn',
  'FCSB',
  'FK Auda',
  'FK Austria Wien',
  'FK Dečić Tuzi',
  'FK Jablonec',
  'FK Kauno Žalgiris',
  'FK Liepaja',
  'FK Mornar Bar',
  'FK Panevėžys',
  'FK Sarajevo',
  'FK Sileks Kratovo',
  'FK Sutjeska Nikšić',
  'FK Vardar Skopje',
  'FK Velež Mostar',
  'FK Vojvodina',
  'FK Žalgiris',
  'FK Železničar Pančevo',
  'Flora Tallinn',
  'Floriana FC',
  'GAIS',
  'GKS Katowice',
  'Getafe',
  'Glentoran FC',
  'Górnik Zabrze',
  'HB Tórshavn',
  'HJK',
  'HNK Hajduk Split',
  'HNK Rijeka',
  'Hammarby IF',
  'Heart of Midlothian',
  'Hibernian',
  'HŠK Zrinjski Mostar',
  'IF Vestri',
  'IFK Göteborg',
  'Ilves',
  "Inter Club d'Escaldes",
  'Inter Turku',
  'Jagiellonia Białystok',
  'KAA Gent',
  'KF Ballkani',
  'KF Egnatia',
  'KF Shkëndija',
  'KF Vllaznia',
  'Klaksvíkar Ítróttarfelag',
  'Kuopion Palloseura',
  'LASK',
  'LNZ Cherkasy',
  'La Fiorita',
  'Larne FC',
  'Lech Poznań',
  'Lillestrøm SK',
  'Lincoln Red Imps',
  'Linfield FC',
  'Ludogorets',
  'ML Vitebsk',
  'Maccabi Tel Aviv',
  'Marsaxlokk FC',
  'Motherwell',
  'MŠK Žilina',
  'NK Aluminij Kidričevo',
  'NK Bravo',
  'NK Celje',
  'NK Varaždin',
  'NSÍ Runavík',
  'Neftçi PFK',
  'Nõmme Kalju',
  'OFI Crete',
  'OFK Petrovac',
  'PAOK',
  'Paide Linnameeskond',
  'Paksi FC',
  'Penybont',
  'Polissya Zhytomyr',
  'Pyunik Yerevan',
  'RFS',
  'Raków Częstochowa',
  'Royale Union Saint-Gilloise',
  'SC Freiburg',
  'SK Brann',
  'SK Rapid Wien',
  'SP Tre Fiori',
  'SS Virtus',
  'Shamrock Rovers',
  'Shelbourne',
  'Sheriff Tiraspol',
  'Sint-Truidense VV',
  'Sporting Braga',
  "St Joseph's FC",
  'Stjarnan Garðabær',
  'TSG Hoffenheim',
  'The New Saints',
  'Torreense',
  'Trabzonspor',
  'Tromsø IL',
  'US Mondorf-Les-Bains',
  'Una Strassen',
  'Universitatea Craiova',
  'Valletta FC',
  'Valur Reykjavík',
  'Víkingur Gøta',
  'Víkingur Reykjavík',
  'Yelimay Semey',
  'Zirə FK',
  'Ħamrun Spartans FC',
]);

test('every club currently present in UEFA qualification feeds has a Russian registry name', () => {
  const missing = CURRENT_FEED_RAW_NAMES.filter(rawName => (
    !isKnownTeamName(rawName) || russianTeamName(rawName) === rawName
  ));

  assert.deepEqual(missing, []);
});

test('current-feed registry keeps common Russian football spellings', () => {
  assert.equal(russianTeamName('Crystal Palace'), 'Кристал Пэлас');
  assert.equal(russianTeamName('Brighton & Hove Albion'), 'Брайтон');
  assert.equal(russianTeamName('PAOK'), 'ПАОК');
  assert.equal(russianTeamName('Sporting Braga'), 'Брага');
  assert.equal(russianTeamName('Royale Union Saint-Gilloise'), 'Юнион Сент-Жиллуаз');
});
