insert into public.cp_team_localizations
  (provider_team_id, name_ru, genitive_ru, dative_ru, prepositional_ru)
values
  ('1', 'Ливерпуль', null, null, null),
  ('2', 'Борнмут', null, null, null),
  ('3', 'Астон Вилла', null, null, null),
  ('5', 'Брайтон', null, null, null),
  ('7', 'Сандерленд', null, null, null),
  ('12', 'Манчестер Сити', null, null, null),
  ('14', 'Кристал Пэлас', null, null, null),
  ('17', 'Манчестер Юнайтед', null, null, null),
  ('18', 'Арсенал', null, null, null),
  ('22', 'Спортинг', null, null, null),
  ('31', 'Брага', null, null, null),
  ('35', 'Порту', null, null, null),
  ('37', 'Бенфика', null, null, null),
  ('41', 'Вильярреал', null, null, null),
  ('44', 'Барселона', null, null, null),
  ('48', 'Реал Сосьедад', null, null, null),
  ('49', 'Сельта', null, null, null),
  ('50', 'Хетафе', null, null, null),
  ('54', 'Атлетико Мадрид', null, null, null),
  ('56', 'Бетис', null, null, null),
  ('57', 'Реал Мадрид', null, null, null),
  ('59', 'Дженоа', 'Дженоа', 'Дженоа', 'Дженоа'),
  ('60', 'Лечче', 'Лечче', 'Лечче', 'Лечче'),
  ('61', 'Сассуоло', 'Сассуоло', 'Сассуоло', 'Сассуоло'),
  ('62', 'Наполи', 'Наполи', 'Наполи', 'Наполи'),
  ('63', 'Милан', 'Милана', 'Милану', 'Милане'),
  ('65', 'Рома', 'Ромы', 'Роме', 'Роме'),
  ('66', 'Болонья', 'Болоньи', 'Болонье', 'Болонье'),
  ('67', 'Кальяри', 'Кальяри', 'Кальяри', 'Кальяри'),
  ('68', 'Фиорентина', 'Фиорентины', 'Фиорентине', 'Фиорентине'),
  ('69', 'Комо', 'Комо', 'Комо', 'Комо'),
  ('70', 'Лацио', 'Лацио', 'Лацио', 'Лацио'),
  ('71', 'Аталанта', 'Аталанты', 'Аталанте', 'Аталанте'),
  ('73', 'Ювентус', 'Ювентуса', 'Ювентусу', 'Ювентусе'),
  ('74', 'Парма', 'Пармы', 'Парме', 'Парме'),
  ('75', 'Удинезе', 'Удинезе', 'Удинезе', 'Удинезе'),
  ('77', 'Интер', 'Интера', 'Интеру', 'Интере'),
  ('78', 'Торино', 'Торино', 'Торино', 'Торино'),
  ('79', 'Бавария', null, null, null),
  ('80', 'РБ Лейпциг', null, null, null),
  ('84', 'Штутгарт', null, null, null),
  ('85', 'Байер', null, null, null),
  ('86', 'Хоффенхайм', null, null, null),
  ('89', 'Фрайбург', null, null, null),
  ('92', 'Боруссия Дортмунд', null, null, null),
  ('97', 'Ренн', null, null, null),
  ('98', 'Марсель', null, null, null),
  ('99', 'Ланс', null, null, null),
  ('100', 'Лион', null, null, null),
  ('101', 'Монако', null, null, null),
  ('106', 'Лилль', null, null, null),
  ('114', 'ПСЖ', null, null, null),
  ('115', 'ПСВ', null, null, null),
  ('116', 'Юнион Сент-Жиллуаз', null, null, null),
  ('118', 'Олимпиакос', null, null, null),
  ('119', 'Пафос', null, null, null),
  ('120', 'Славия Прага', null, null, null),
  ('121', 'Будё-Глимт', null, null, null),
  ('122', 'Аякс', null, null, null),
  ('123', 'Брюгге', null, null, null),
  ('124', 'Копенгаген', null, null, null),
  ('125', 'Галатасарай', null, null, null),
  ('126', 'Кайрат', null, null, null),
  ('127', 'Мидтьюлланн', null, null, null),
  ('128', 'Штурм', null, null, null),
  ('131', 'Црвена Звезда', null, null, null),
  ('132', 'Селтик', null, null, null),
  ('133', 'Динамо Загреб', null, null, null),
  ('134', 'Фенербахче', null, null, null),
  ('138', 'Фейеноорд', null, null, null),
  ('141', 'Бранн', null, null, null),
  ('143', 'Ференцварош', null, null, null),
  ('144', 'Виктория Пльзень', null, null, null),
  ('147', 'Зальцбург', null, null, null),
  ('149', 'Панатинаикос', null, null, null),
  ('171', 'НЕК Неймеген', null, null, null),
  ('178', 'Твенте', null, null, null),
  ('180', 'АЗ Алкмар', null, null, null),
  ('196', 'Бешикташ', null, null, null),
  ('197', 'Трабзонспор', null, null, null),
  ('231', 'Хартс', null, null, null),
  ('240', 'Андерлехт', null, null, null),
  ('244', 'Сент-Трюйден', null, null, null),
  ('245', 'Гент', null, null, null),
  ('254', 'Лугано', null, null, null),
  ('255', 'Тун', null, null, null),
  ('329', 'АЕК Афины', null, null, null),
  ('332', 'ОФИ', null, null, null),
  ('345', 'ЦСКА София', null, null, null),
  ('348', 'Левски', null, null, null),
  ('359', 'Университатя Крайова', null, null, null),
  ('374', 'Слован Братислава', null, null, null),
  ('375', 'Лех', null, null, null),
  ('377', 'КуПС', null, null, null),
  ('382', 'Линкольн Ред Импс', null, null, null),
  ('395', 'Иберия 1999', null, null, null),
  ('398', 'Интер Эскальдес', null, null, null),
  ('401', 'Эгнатия', null, null, null),
  ('402', 'Шахтёр Донецк', null, null, null),
  ('406', 'Целе', null, null, null),
  ('412', 'Сабах', null, null, null),
  ('416', 'Хапоэль Беэр-Шева', null, null, null),
  ('420', 'Ягеллония', null, null, null),
  ('441', 'Мьельбю', null, null, null),
  ('1277', 'Фрозиноне', 'Фрозиноне', 'Фрозиноне', 'Фрозиноне'),
  ('1285', 'Венеция', 'Венеции', 'Венеции', 'Венеции'),
  ('1286', 'Монца', 'Монцы', 'Монце', 'Монце'),
  ('1332', 'Норшелланн', null, null, null),
  ('1340', 'Спарта Прага', null, null, null),
  ('1404', 'ЛАСК', null, null, null),
  ('2076', 'Викинг', null, null, null),
  ('2081', 'Лиллестрём', null, null, null),
  ('2213', 'Торреэнсе', null, null, null),
  ('2313', 'Борац Баня-Лука', null, null, null),
  ('2343', 'Хайдук', null, null, null),
  ('2346', 'Омония', null, null, null),
  ('2372', 'АГФ', null, null, null),
  ('2838', 'Рига', null, null, null),
  ('3298', 'Арарат-Армения', null, null, null),
  ('3575', 'Кауно Жальгирис', null, null, null),
  ('4078', 'Яблонец', null, null, null)
on conflict (provider_team_id) do update set
  name_ru = excluded.name_ru,
  genitive_ru = excluded.genitive_ru,
  dative_ru = excluded.dative_ru,
  prepositional_ru = excluded.prepositional_ru,
  updated_at = now();
